export const projects = [
  {
    id: "1",
    icon: "/assets/github.svg",
    title: "Autograder",
    desc: "For my dissertation, I developed a RESTful Autograder web application (automatic grading of programming assignment using test cases) that can be integrated into LMS (e.g., Canvas) using REST API.",
    img: "/assets/autograder-2.png",
    link: "https://github.com/fmlog/Autograder-v2",
  },
  {
    id: "2",
    icon: "/assets/github.svg",
    title: "Sed Michael Website",
    desc: "Rebuilt the website of the agency I run from the ground up. The new website offers more extensibilty than the existing Squarespace website agency. The website was implemented with Next.js and React.",
    img: "/assets/sed-michael.png",
    link: "https://github.com/fmlog/Autograder-v2",
  },
  {
    id: "3",
    icon: "/assets/github.svg",
    title: "Autograder3",
    desc: "For my dissertation, I developed a RESTful Autograder web application (automatic grading of programming assignment using test cases) that can be integrated into LMS (e.g., Canvas) using REST API.",
    img: "/assets/autograder.png",
    link: "https://github.com/fmlog/Autograder-v2",
  },
  {
    id: "4",
    icon: "/assets/github.svg",
    title: "Sed Michael Website",
    desc: "Rebuilt the website of the agency I run from the ground up. The new website offers more extensibilty than the existing Squarespace website agency. The website was implemented with Next.js and React.",
    img: "/assets/sed-michael.png",
    link: "https://github.com/fmlog/Autograder-v2",
  },
  {
    id: "5",
    icon: "/assets/github.svg",
    title: "Sed Michael Website",
    desc: "Rebuilt the website of the agency I run from the ground up. The new website offers more extensibilty than the existing Squarespace website agency. The website was implemented with Next.js and React.",
    img: "/assets/sed-michael.png",
    link: "https://github.com/fmlog/Autograder-v2",
  },
];
